name: Build and Deploy Microfrontend App

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define a matrix to build and test each microfrontend separately
        microfrontend: 
          - lib1
          - shell
          - mfe1
          - mfe2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'
      
      - name: Authenticate with GitHub Package Registry
        # run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > ~/.npmrc    

    # Cache node_modules to speed up build process
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Navigate to each microfrontend directory and install dependencies
      - name: Install dependencies
        run: npm install

      # Build each microfrontend
      - name: Build project
        run: npm run build ${{ matrix.microfrontend }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.microfrontend }}-build-artifacts
          path: dist/${{ matrix.microfrontend }}

  deploy:
    needs:  build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define a matrix to build and test each microfrontend separately
        microfrontend: 
          - lib1
          - shell
          - mfe1
          - mfe2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.microfrontend }}-build-artifacts
          path: dist/${{ matrix.microfrontend }}

      # Deploy steps here
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
