name: Build and Test Angular Microfrontend Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Define a matrix to build and test each microfrontend separately
        microfrontend: 
          - shell
          - mfe1
          - mfe2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Cache node_modules to speed up build process
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Navigate to each microfrontend directory and install dependencies
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: |
        cd projects
        cd ${{ matrix.microfrontend }}
        ng build ${{ matrix.microfrontend }}
