name: Compare and Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  compare-and-create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'raselahmed09'
          git config --global user.email 'rasel.ict09@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Check for differences
        id: diff
        run: |
          git diff --exit-code origin/main..origin/dev || echo "::set-output name=diff::true"

      - name: Create Pull Request
        if: steps.diff.outputs.diff == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: dev
          title: 'Sync dev with main'
          body: 'This is an automated pull request to sync changes from the dev branch to the main branch.'
          draft: false
