name: Compare and Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  compare-and-create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Check for differences
        id: diff
        run: |
          if git diff --quiet origin/main..origin/dev; then
            echo "No changes to synchronize."
            echo "::set-output name=diff::false"
          else
            echo "Changes detected."
            echo "::set-output name=diff::true"
          fi

      - name: Create Pull Request
        if: steps.diff.outputs.diff == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: dev
          title: 'Sync dev with main'
          body: |
            This is an automated pull request to sync changes from the dev branch to the main branch.
            Changes include:
            ${{ steps.diff.outputs.diff_output }}
          draft: false