name: Merge dev to main

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Merge dev into main
      run: git merge --no-ff origin/dev -m "Merge dev into main"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
